[book]
authors = ["Sebastien Delpeuch"]
language = "en"
multilingual = false

src = "src"
title = "Ronoco-documentation"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]


[output.html]
default-theme = "ayu"
fold.enable = true
